repos:
  # Pre-commit hooks for general checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer    # Ensure files end with a newline
      - id: check-yaml           # Check YAML files for syntax errors
      - id: detect-private-key   # Detect private keys
  # Pre-commit hook for Black (Python code formatter)
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
  # Pre-commit hook for isort (Python import sorter)
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  # Pre-commit hook for mypy (static type checker for Python)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
  # Pre-commit hook for flake8 (Python code linter)
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2
    hooks:
      - id: flake8
  # Pre-commit hook for bandit (security linter for Python)
  - repo: https://github.com/pre-commit/mirrors-bandit
    rev: v1.7.0
    hooks:
      - id: bandit
